[book]
title = "Archict documentation"
authors = ["Kevin Traini <kevin@ktraini.com>"]
description = "Documentation of Archict PHP framework"
src = "src"
language = "en"
multilingual = false

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/Archict/documentation"
edit-url-template  = "https://github.com/Archict/documentation/edit/master/{path}"

[preprocessor.alerts]

[preprocessor.webinclude]
